name: Release Image
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "azuki-bar"
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Tags
        id: vars
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "image_tag=${SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/azuki-bar/switchbot-mackerel:${{ steps.vars.outputs.image_tag }}
          platforms: linux/amd64,linux/arm64
          provenance: false
